### ISSUE TITLE
TweepError: File is too big, must be less than 3072kb.

### ISSUE THREAD

**Issue by seanauriti** [Bugheist/website#49]
View details in Rollbar: [https://rollbar.com/bugheist/Bugheist/items/24/](https://rollbar.com/bugheist/Bugheist/items/24/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/edit.py", line 256, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/edit.py", line 222, in post
    return self.form_valid(form)
  File "/app/website/views.py", line 75, in form_valid
    obj.save()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 737, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/app/website/models.py", line 138, in post_to_twitter
    media_ids = api.media_upload(filename=instance.screenshot.file.name, file=file)
  File "/app/.heroku/python/lib/python2.7/site-packages/tweepy/api.py", line 201, in media_upload
    headers, post_data = API._pack_image(filename, 3072, form_field='media', f=f)
  File "/app/.heroku/python/lib/python2.7/site-packages/tweepy/api.py", line 1313, in _pack_image
    raise TweepError('File is too big, must be less than %skb.' % max_size)
TweepError: File is too big, must be less than 3072kb.
```

**Comment by seanauriti** [comment]
This was found by @RamiSaleem  because the image was too big for twitter... We've added an image size validation now.
