### ISSUE TITLE
TweepError: [{u'message': u'Status is over 140 characters.', u'code': 186}]

### ISSUE THREAD

**Issue by seanauriti** [Bugheist/website#89]
View details in Rollbar: [https://rollbar.com/bugheist/Bugheist/items/33/](https://rollbar.com/bugheist/Bugheist/items/33/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/edit.py", line 256, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/views/generic/edit.py", line 222, in post
    return self.form_valid(form)
  File "/app/website/views.py", line 72, in form_valid
    obj.screenshot.save(self.request.POST.get('screenshot-hash') +'.png', django_file, save=True)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/fields/files.py", line 111, in save
    self.instance.save()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 737, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/app/website/models.py", line 148, in post_to_twitter
    api.update_status(**params)
  File "/app/.heroku/python/lib/python2.7/site-packages/tweepy/api.py", line 194, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/tweepy/binder.py", line 245, in _call
    return method.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/tweepy/binder.py", line 229, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
TweepError: [{u'message': u'Status is over 140 characters.', u'code': 186}]
```

**Comment by seanauriti** [comment]
Seems the status was only 139 chars.  Not sure why this happened.
params	{
"media_ids": [
"799486222225772544"
],
"status": "Bug found on @Bugheist | domain is not adding correctly. reported an issue on beta.dweet.io and the domain is http://bugheist.com/issue/225"
}
